version: '3'

services:

  db:
    image: "postgres:alpine"
    container_name: db
    volumes:
      - smart-house-date:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: smart-house
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  smart-house:
    build: .

    environment:
      DB_SERVER: db
      POSTGRES_DB: smart-house
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8082:8082
    links:
      - db
    depends_on:
      - db

volumes:
  smart-house-date: